services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: proceedings
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
      
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672" # used by Spring application
      - "15672:15672" # used for management interface
